<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DRACULA" failures="20" tests="25" name="Testcase_RegisterUser" time="693.754" errors="0" timestamp="2021-12-09T18:28:13 IST">
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithValidData" time="22.584"/>
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithValidData" time="22.903">
    <failure type="java.lang.AssertionError" message="expected [OTP Sent on Email!!] but found [Email Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [OTP Sent on Email!!] but found [Email Already Exists]
at po.Po_RegisterUser.User_RegisterWithValidData(Po_RegisterUser.java:243)
at testcase.Testcase_RegisterUser.UserRegisterwithValidData(Testcase_RegisterUser.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithValidData -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithValidData" time="23.159">
    <failure type="java.lang.AssertionError" message="expected [OTP Sent on Email!!] but found [Phone # Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [OTP Sent on Email!!] but found [Phone # Already Exists]
at po.Po_RegisterUser.User_RegisterWithValidData(Po_RegisterUser.java:243)
at testcase.Testcase_RegisterUser.UserRegisterwithValidData(Testcase_RegisterUser.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithValidData -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithValidData" time="22.991">
    <failure type="java.lang.AssertionError" message="expected [OTP Sent on Email!!] but found [Please use a valid mobile number]">
      <![CDATA[java.lang.AssertionError: expected [OTP Sent on Email!!] but found [Please use a valid mobile number]
at po.Po_RegisterUser.User_RegisterWithValidData(Po_RegisterUser.java:243)
at testcase.Testcase_RegisterUser.UserRegisterwithValidData(Testcase_RegisterUser.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithValidData -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithValidData" time="22.555">
    <failure type="java.lang.AssertionError" message="expected [OTP Sent on Email!!] but found [Birthday should be DD-MM-YYYY]">
      <![CDATA[java.lang.AssertionError: expected [OTP Sent on Email!!] but found [Birthday should be DD-MM-YYYY]
at po.Po_RegisterUser.User_RegisterWithValidData(Po_RegisterUser.java:243)
at testcase.Testcase_RegisterUser.UserRegisterwithValidData(Testcase_RegisterUser.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithValidData -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithexisitingEmailID" time="23.431">
    <failure type="java.lang.AssertionError" message="expected [Email Already Exists] but found [OTP Sent on Email!!]">
      <![CDATA[java.lang.AssertionError: expected [Email Already Exists] but found [OTP Sent on Email!!]
at po.Po_RegisterUser.User_RegisterWithExistingEmailid(Po_RegisterUser.java:286)
at testcase.Testcase_RegisterUser.UserRegisterwithexisitingEmailID(Testcase_RegisterUser.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithexisitingEmailID -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithexisitingEmailID" time="22.568"/>
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithexisitingEmailID" time="22.702">
    <failure type="java.lang.AssertionError" message="expected [Email Already Exists] but found [Phone # Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Email Already Exists] but found [Phone # Already Exists]
at po.Po_RegisterUser.User_RegisterWithExistingEmailid(Po_RegisterUser.java:286)
at testcase.Testcase_RegisterUser.UserRegisterwithexisitingEmailID(Testcase_RegisterUser.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithexisitingEmailID -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithexisitingEmailID" time="22.973">
    <failure type="java.lang.AssertionError" message="expected [Email Already Exists] but found [Please use a valid mobile number]">
      <![CDATA[java.lang.AssertionError: expected [Email Already Exists] but found [Please use a valid mobile number]
at po.Po_RegisterUser.User_RegisterWithExistingEmailid(Po_RegisterUser.java:286)
at testcase.Testcase_RegisterUser.UserRegisterwithexisitingEmailID(Testcase_RegisterUser.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithexisitingEmailID -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithexisitingEmailID" time="22.484">
    <failure type="java.lang.AssertionError" message="expected [Email Already Exists] but found [Birthday should be DD-MM-YYYY]">
      <![CDATA[java.lang.AssertionError: expected [Email Already Exists] but found [Birthday should be DD-MM-YYYY]
at po.Po_RegisterUser.User_RegisterWithExistingEmailid(Po_RegisterUser.java:286)
at testcase.Testcase_RegisterUser.UserRegisterwithexisitingEmailID(Testcase_RegisterUser.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithexisitingEmailID -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithExistingPhoneNo" time="22.811">
    <failure type="java.lang.AssertionError" message="expected [Phone # Already Exists] but found [OTP Sent on Email!!]">
      <![CDATA[java.lang.AssertionError: expected [Phone # Already Exists] but found [OTP Sent on Email!!]
at po.Po_RegisterUser.User_RegisterWithExistingPhoneNumber(Po_RegisterUser.java:328)
at testcase.Testcase_RegisterUser.UserRegisterwithExistingPhoneNo(Testcase_RegisterUser.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithExistingPhoneNo -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithExistingPhoneNo" time="22.855">
    <failure type="java.lang.AssertionError" message="expected [Phone # Already Exists] but found [Email Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Phone # Already Exists] but found [Email Already Exists]
at po.Po_RegisterUser.User_RegisterWithExistingPhoneNumber(Po_RegisterUser.java:328)
at testcase.Testcase_RegisterUser.UserRegisterwithExistingPhoneNo(Testcase_RegisterUser.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithExistingPhoneNo -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithExistingPhoneNo" time="22.7"/>
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithExistingPhoneNo" time="23.41">
    <failure type="java.lang.AssertionError" message="expected [Phone # Already Exists] but found [Please use a valid mobile number]">
      <![CDATA[java.lang.AssertionError: expected [Phone # Already Exists] but found [Please use a valid mobile number]
at po.Po_RegisterUser.User_RegisterWithExistingPhoneNumber(Po_RegisterUser.java:328)
at testcase.Testcase_RegisterUser.UserRegisterwithExistingPhoneNo(Testcase_RegisterUser.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithExistingPhoneNo -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithExistingPhoneNo" time="22.395">
    <failure type="java.lang.AssertionError" message="expected [Phone # Already Exists] but found [Birthday should be DD-MM-YYYY]">
      <![CDATA[java.lang.AssertionError: expected [Phone # Already Exists] but found [Birthday should be DD-MM-YYYY]
at po.Po_RegisterUser.User_RegisterWithExistingPhoneNumber(Po_RegisterUser.java:328)
at testcase.Testcase_RegisterUser.UserRegisterwithExistingPhoneNo(Testcase_RegisterUser.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithExistingPhoneNo -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidPhoneNumber" time="22.668">
    <failure type="java.lang.AssertionError" message="expected [Please use a valid mobile number] but found [OTP Sent on Email!!]">
      <![CDATA[java.lang.AssertionError: expected [Please use a valid mobile number] but found [OTP Sent on Email!!]
at po.Po_RegisterUser.User_RegisterWithInvalidPhonenumber(Po_RegisterUser.java:371)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidPhoneNumber(Testcase_RegisterUser.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidPhoneNumber -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidPhoneNumber" time="22.651">
    <failure type="java.lang.AssertionError" message="expected [Please use a valid mobile number] but found [Email Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Please use a valid mobile number] but found [Email Already Exists]
at po.Po_RegisterUser.User_RegisterWithInvalidPhonenumber(Po_RegisterUser.java:371)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidPhoneNumber(Testcase_RegisterUser.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidPhoneNumber -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidPhoneNumber" time="22.397">
    <failure type="java.lang.AssertionError" message="expected [Please use a valid mobile number] but found [Phone # Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Please use a valid mobile number] but found [Phone # Already Exists]
at po.Po_RegisterUser.User_RegisterWithInvalidPhonenumber(Po_RegisterUser.java:371)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidPhoneNumber(Testcase_RegisterUser.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidPhoneNumber -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidPhoneNumber" time="22.287"/>
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidPhoneNumber" time="22.245">
    <failure type="java.lang.AssertionError" message="expected [Please use a valid mobile number] but found [Birthday should be DD-MM-YYYY]">
      <![CDATA[java.lang.AssertionError: expected [Please use a valid mobile number] but found [Birthday should be DD-MM-YYYY]
at po.Po_RegisterUser.User_RegisterWithInvalidPhonenumber(Po_RegisterUser.java:371)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidPhoneNumber(Testcase_RegisterUser.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidPhoneNumber -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidBirthDate" time="24.301">
    <failure type="java.lang.AssertionError" message="expected [Birthday should be DD-MM-YYYY] but found [OTP Sent on Email!!]">
      <![CDATA[java.lang.AssertionError: expected [Birthday should be DD-MM-YYYY] but found [OTP Sent on Email!!]
at po.Po_RegisterUser.User_RegisterWithInvalidBirthdate(Po_RegisterUser.java:415)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidBirthDate(Testcase_RegisterUser.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidBirthDate -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidBirthDate" time="24.576">
    <failure type="java.lang.AssertionError" message="expected [Birthday should be DD-MM-YYYY] but found [Email Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Birthday should be DD-MM-YYYY] but found [Email Already Exists]
at po.Po_RegisterUser.User_RegisterWithInvalidBirthdate(Po_RegisterUser.java:415)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidBirthDate(Testcase_RegisterUser.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidBirthDate -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidBirthDate" time="24.4">
    <failure type="java.lang.AssertionError" message="expected [Birthday should be DD-MM-YYYY] but found [Phone # Already Exists]">
      <![CDATA[java.lang.AssertionError: expected [Birthday should be DD-MM-YYYY] but found [Phone # Already Exists]
at po.Po_RegisterUser.User_RegisterWithInvalidBirthdate(Po_RegisterUser.java:415)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidBirthDate(Testcase_RegisterUser.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidBirthDate -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidBirthDate" time="24.532">
    <failure type="java.lang.AssertionError" message="expected [Birthday should be DD-MM-YYYY] but found [Please use a valid mobile number]">
      <![CDATA[java.lang.AssertionError: expected [Birthday should be DD-MM-YYYY] but found [Please use a valid mobile number]
at po.Po_RegisterUser.User_RegisterWithInvalidBirthdate(Po_RegisterUser.java:415)
at testcase.Testcase_RegisterUser.UserRegisterwithInvalidBirthDate(Testcase_RegisterUser.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UserRegisterwithInvalidBirthDate -->
  <testcase classname="testcase.Testcase_RegisterUser" name="UserRegisterwithInvalidBirthDate" time="23.996"/>
</testsuite> <!-- Testcase_RegisterUser -->
